spring.application.name=LabManager - API

spring.datasource.url=jdbc:postgresql://localhost:5432/labmanager
spring.datasource.username=postgres
spring.datasource.password=42886363wbR#

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect